package xml

import "encoding/xml"
// AUTOGENERATED USING ZEK over entire corpus

type ClinicalStudyGuido struct {
	XMLName        xml.Name `xml:"clinical_study"`
	Text           string   `xml:",chardata"`
	Rank           string   `xml:"rank,attr"`
	RequiredHeader struct {
		Text         string `xml:",chardata"`
		DownloadDate string `xml:"download_date"` // ClinicalTrials.gov proces...
		LinkText     string `xml:"link_text"`     // Link to the current Clini...
		URL          string `xml:"url"`           // https://clinicaltrials.go...
	} `xml:"required_header"`
	IDInfo struct {
		Text        string   `xml:",chardata"`
		OrgStudyID  string   `xml:"org_study_id"` // D3551C00003, ARDS1, 31171...
		NctID       string   `xml:"nct_id"`       // NCT01890148, NCT01289600,...
		SecondaryID []string `xml:"secondary_id"` // RV-AMYL-PI-0375, SU-09192...
		NctAlias    []string `xml:"nct_alias"`    // NCT00019370, NCT00044850,...
	} `xml:"id_info"`
	BriefTitle    string `xml:"brief_title"`    // Distribution of Neutrophi...
	OfficialTitle string `xml:"official_title"` // An Explorative Investigat...
	Sponsors      struct {
		Text        string `xml:",chardata"`
		LeadSponsor struct {
			Text        string `xml:",chardata"`
			Agency      string `xml:"agency"`       // AstraZeneca, University M...
			AgencyClass string `xml:"agency_class"` // Industry, Other, Other, O...
		} `xml:"lead_sponsor"`
		Collaborator []struct {
			Text        string `xml:",chardata"`
			Agency      string `xml:"agency"`       // Children's Miracle Networ...
			AgencyClass string `xml:"agency_class"` // Other, Industry, Industry...
		} `xml:"collaborator"`
	} `xml:"sponsors"`
	Source        string `xml:"source"` // AstraZeneca, University M...
	OversightInfo struct {
		Text      string   `xml:",chardata"`
		Authority []string `xml:"authority"` // Germany: Federal Institut...
		HasDmc    string   `xml:"has_dmc"`   // No, Yes, Yes, Yes, Yes, N...
	} `xml:"oversight_info"`
	BriefSummary struct {
		Text      string `xml:",chardata"`
		Textblock string `xml:"textblock"` // Distribution of neutrophi...
	} `xml:"brief_summary"`
	DetailedDescription struct {
		Text      string `xml:",chardata"`
		Textblock string `xml:"textblock"` // The purpose is to investi...
	} `xml:"detailed_description"`
	OverallStatus  string `xml:"overall_status"` // Completed, Completed, Rec...
	StartDate      string `xml:"start_date"`     // March 2014, January 2011,...
	CompletionDate struct {
		Text string `xml:",chardata"` // August 2014, March 2013, ...
		Type string `xml:"type,attr"`
	} `xml:"completion_date"`
	PrimaryCompletionDate struct {
		Text string `xml:",chardata"` // August 2014, March 2013, ...
		Type string `xml:"type,attr"`
	} `xml:"primary_completion_date"`
	Phase          string `xml:"phase"`        // Phase 1, N/A, Phase 4, N/...
	StudyType      string `xml:"study_type"`   // Interventional, Intervent...
	StudyDesign    string `xml:"study_design"` // Allocation: Non-Randomize...
	PrimaryOutcome []struct {
		Text        string `xml:",chardata"`
		Measure     string `xml:"measure"`      // Description of pharmacody...
		TimeFrame   string `xml:"time_frame"`   // Sample at baseline (withi...
		SafetyIssue string `xml:"safety_issue"` // No, No, No, No, No, No, Y...
		Description string `xml:"description"`  // log change from baseline,...
	} `xml:"primary_outcome"`
	SecondaryOutcome []struct {
		Text        string `xml:",chardata"`
		Measure     string `xml:"measure"`      // Description of pharmacody...
		TimeFrame   string `xml:"time_frame"`   // Sample at baseline (withi...
		SafetyIssue string `xml:"safety_issue"` // No, No, No, No, No, No, N...
		Description string `xml:"description"`  // Log Change from baseline,...
	} `xml:"secondary_outcome"`
	NumberOfArms string `xml:"number_of_arms"` // 1, 4, 2, 1, 4, 1, 4, 2, 3...
	Enrollment   struct {
		Text string `xml:",chardata"` // 14, 12, 30, 25, 70, 120, ...
		Type string `xml:"type,attr"`
	} `xml:"enrollment"`
	Condition []string `xml:"condition"` // Asthma, ARDS, Fontan Circ...
	ArmGroup  []struct {
		Text          string `xml:",chardata"`
		ArmGroupLabel string `xml:"arm_group_label"` // 1, Pressure support venti...
		ArmGroupType  string `xml:"arm_group_type"`  // Experimental, Active Comp...
		Description   string `xml:"description"`     // oral BD administration of...
	} `xml:"arm_group"`
	Intervention []struct {
		Text             string   `xml:",chardata"`
		InterventionType string   `xml:"intervention_type"` // Drug, Device, Drug, Other...
		InterventionName string   `xml:"intervention_name"` // AZD5069, Mechanical venti...
		Description      string   `xml:"description"`       // oral BD administration of...
		ArmGroupLabel    []string `xml:"arm_group_label"`   // 1, Pressure support venti...
		OtherName        []string `xml:"other_name"`        // Maquet Servo-i, Viagra, C...
	} `xml:"intervention"`
	Eligibility struct {
		Text     string `xml:",chardata"`
		Criteria struct {
			Text      string `xml:",chardata"`
			Textblock string `xml:"textblock"` // Inclusion Criteria:      ...
		} `xml:"criteria"`
		Gender            string `xml:"gender"`             // Both, Both, Both, Both, B...
		MinimumAge        string `xml:"minimum_age"`        // 18 Years, 18 Years, 6 Yea...
		MaximumAge        string `xml:"maximum_age"`        // 65 Years, N/A, 17 Years, ...
		HealthyVolunteers string `xml:"healthy_volunteers"` // No, No, Accepts Healthy V...
		StudyPop          struct {
			Text      string `xml:",chardata"`
			Textblock string `xml:"textblock"` // Caregivers and patients w...
		} `xml:"study_pop"`
		SamplingMethod string `xml:"sampling_method"` // Non-Probability Sample, P...
	} `xml:"eligibility"`
	OverallOfficial []struct {
		Text        string `xml:",chardata"`
		LastName    string `xml:"last_name"`   // Kai Richter, MSD, Klaus F...
		Role        string `xml:"role"`        // Study Director, Principal...
		Affiliation string `xml:"affiliation"` // Astrazeneca Sweden, Lung ...
	} `xml:"overall_official"`
	Location []struct {
		Text     string `xml:",chardata"`
		Facility struct {
			Text    string `xml:",chardata"`
			Name    string `xml:"name"` // Research Site, University...
			Address struct {
				Text    string `xml:",chardata"`
				City    string `xml:"city"`    // Grosshansdorf, Nijmegen, ...
				Country string `xml:"country"` // Germany, Netherlands, Uni...
				State   string `xml:"state"`   // Gelderland, Pennsylvania,...
				Zip     string `xml:"zip"`     // 6525 GA, 17033, 94305, 62...
			} `xml:"address"`
		} `xml:"facility"`
		Status  string `xml:"status"` // Recruiting, Recruiting, N...
		Contact struct {
			Text     string `xml:",chardata"`
			LastName string `xml:"last_name"` // Chowdhury, Judith M. Wish...
			Email    string `xml:"email"`     // dchowdhury@hmc.psu.edu, j...
			Phone    string `xml:"phone"`     // 352-494-3165, 86136017673...
			PhoneExt string `xml:"phone_ext"` // 3, 2013, 271, =, 44506, 3...
		} `xml:"contact"`
		Investigator []struct {
			Text     string `xml:",chardata"`
			LastName string `xml:"last_name"` // Devyani Chowdhury, MD, St...
			Role     string `xml:"role"`      // Principal Investigator, S...
		} `xml:"investigator"`
		ContactBackup struct {
			Text     string `xml:",chardata"`
			LastName string `xml:"last_name"` // Azra Bihorac, MD, Jie Che...
			Phone    string `xml:"phone"`     // 352-273-9009, 86137646335...
			Email    string `xml:"email"`     // abihorac@anest.ufl.edu, c...
			PhoneExt string `xml:"phone_ext"` // 88441, 2117, 23641, 35001...
		} `xml:"contact_backup"`
	} `xml:"location"`
	LocationCountries struct {
		Text    string   `xml:",chardata"`
		Country []string `xml:"country"` // Germany, Netherlands, Uni...
	} `xml:"location_countries"`
	VerificationDate  string `xml:"verification_date"`  // September 2014, June 2015...
	LastchangedDate   string `xml:"lastchanged_date"`   // September 17, 2014, June ...
	FirstreceivedDate string `xml:"firstreceived_date"` // June 17, 2013, January 27...
	ResponsibleParty  struct {
		Text                    string `xml:",chardata"`
		ResponsiblePartyType    string `xml:"responsible_party_type"`   // Sponsor, Principal Invest...
		InvestigatorAffiliation string `xml:"investigator_affiliation"` // University Medical Center...
		InvestigatorFullName    string `xml:"investigator_full_name"`   // Leo Heunks, Stanley L Sch...
		InvestigatorTitle       string `xml:"investigator_title"`       // MD PhD, Professor of Medi...
		NameTitle               string `xml:"name_title"`               // Devyani Chowdhury/MD, Sar...
		Organization            string `xml:"organization"`             // Penn State Hershey Medica...
	} `xml:"responsible_party"`
	Keyword           []string `xml:"keyword"`             // Asthma, Fontan, sildenafi...
	IsFdaRegulated    string   `xml:"is_fda_regulated"`    // No, No, Yes, No, Yes, No,...
	HasExpandedAccess string   `xml:"has_expanded_access"` // No, No, No, No, No, No, N...
	ConditionBrowse   struct {
		Text     string   `xml:",chardata"`
		MeshTerm []string `xml:"mesh_term"` // Asthma, Acute Lung Injury...
	} `xml:"condition_browse"`
	OverallContact struct {
		Text     string `xml:",chardata"`
		LastName string `xml:"last_name"` // Devyani Chowdhury, MD, Ha...
		Phone    string `xml:"phone"`     // 717-531-6847, 713-792-702...
		Email    string `xml:"email"`     // dchowdhury@hmc.psu.edu, j...
		PhoneExt string `xml:"phone_ext"` // 208, 3, 2013, 88441, 6355...
	} `xml:"overall_contact"`
	OverallContactBackup struct {
		Text     string `xml:",chardata"`
		LastName string `xml:"last_name"` // Matthew S. Dean, MS, Azra...
		Phone    string `xml:"phone"`     // 717-531-1847, 352-273-900...
		Email    string `xml:"email"`     // mdean@psu.edu, abihorac@a...
		PhoneExt string `xml:"phone_ext"` // 88441, 3193, 23641, 44348...
	} `xml:"overall_contact_backup"`
	IsSection801       string `xml:"is_section_801"` // Yes, Yes, No, No, Yes, Ye...
	InterventionBrowse struct {
		Text     string   `xml:",chardata"`
		MeshTerm []string `xml:"mesh_term"` // Sildenafil, BB 1101, Dexa...
	} `xml:"intervention_browse"`
	Link []struct {
		Text        string `xml:",chardata"`
		URL         string `xml:"url"`         // http://www.mdanderson.org...
		Description string `xml:"description"` // University of Texas MD An...
	} `xml:"link"`
	Acronym      string `xml:"acronym"` // ICU_Delirium, Armodafinil...
	OtherOutcome []struct {
		Text        string `xml:",chardata"`
		Measure     string `xml:"measure"`      // Facial amimia versus non-...
		TimeFrame   string `xml:"time_frame"`   // Changes from Baseline up ...
		SafetyIssue string `xml:"safety_issue"` // No, No, No, No, Yes, No, ...
		Description string `xml:"description"`  // Frequency of presence of ...
	} `xml:"other_outcome"`
	WhyStopped               string `xml:"why_stopped"`                // Difficulty with recruitme...
	FirstreceivedResultsDate string `xml:"firstreceived_results_date"` // July 30, 2014, November 1...
	NumberOfGroups           string `xml:"number_of_groups"`           // 1, 2, 1, 1, 1, 1, 3, 1, 1...
	RemovedCountries         struct {
		Text    string   `xml:",chardata"`
		Country []string `xml:"country"` // United States, Peru, Phil...
	} `xml:"removed_countries"`
	Reference []struct {
		Text     string `xml:",chardata"`
		Citation string `xml:"citation"` // Janssens JP, Metzger M, S...
		PMID     string `xml:"PMID"`     // 18579368, 25200570, 98136...
	} `xml:"reference"`
	ResultsReference []struct {
		Text     string `xml:",chardata"`
		Citation string `xml:"citation"` // Yi JH, Liu HB, Zhang M, W...
		PMID     string `xml:"PMID"`     // 22205619, 19308287, 17981...
	} `xml:"results_reference"`
	BiospecRetention string `xml:"biospec_retention"` // Samples Without DNA, Samp...
	BiospecDescr     struct {
		Text      string `xml:",chardata"`
		Textblock string `xml:"textblock"` // Retaining serum and plasm...
	} `xml:"biospec_descr"`
	TargetDuration string `xml:"target_duration"` // 30 Days, 1 Week, 90 Days,...
}

type ClinicalStudy struct {
	XMLName        xml.Name `xml:"clinical_study"`
	Text           string   `xml:",chardata"`
	RequiredHeader struct {
		Text         string `xml:",chardata"`
		DownloadDate string `xml:"download_date"` // ClinicalTrials.gov proces...
		LinkText     string `xml:"link_text"`     // Link to the current Clini...
		URL          string `xml:"url"`           // https://clinicaltrials.go...
	} `xml:"required_header"`
	IDInfo struct {
		Text        string   `xml:",chardata"`
		OrgStudyID  string   `xml:"org_study_id"` // NCRR-M01RR01070-0506, NCR...
		SecondaryID []string `xml:"secondary_id"` // M01RR001070, M01RR000400,...
		NctID       string   `xml:"nct_id"`       // NCT00000102, NCT00000104,...
		NctAlias    []string `xml:"nct_alias"`    // NCT00001312, NCT00000247,...
	} `xml:"id_info"`
	BriefTitle string `xml:"brief_title"` // Congenital Adrenal Hyperp...
	Sponsors   struct {
		Text        string `xml:",chardata"`
		LeadSponsor struct {
			Text        string `xml:",chardata"`
			Agency      string `xml:"agency"`       // National Center for Resea...
			AgencyClass string `xml:"agency_class"` // NIH, NIH, Other, NIH, NIH...
		} `xml:"lead_sponsor"`
		Collaborator []struct {
			Text        string `xml:",chardata"`
			Agency      string `xml:"agency"`       // HRSA/Maternal and Child H...
			AgencyClass string `xml:"agency_class"` // U.S. Fed, NIH, NIH, NIH, ...
		} `xml:"collaborator"`
	} `xml:"sponsors"`
	Source       string `xml:"source"` // National Center for Resea...
	BriefSummary struct {
		Text      string `xml:",chardata"`
		Textblock string `xml:"textblock"` // This study will test the ...
	} `xml:"brief_summary"`
	DetailedDescription struct {
		Text      string `xml:",chardata"`
		Textblock string `xml:"textblock"` // This protocol is designed...
	} `xml:"detailed_description"`
	OverallStatus     string `xml:"overall_status"`      // Completed, Completed, Ter...
	Phase             string `xml:"phase"`               // Phase 1/Phase 2, N/A, N/A...
	StudyType         string `xml:"study_type"`          // Interventional, Observati...
	HasExpandedAccess string `xml:"has_expanded_access"` // No, No, No, No, No, No, N...
	StudyDesignInfo   struct {
		Text                         string `xml:",chardata"`
		InterventionModel            string `xml:"intervention_model"`             // Parallel Assignment, Para...
		PrimaryPurpose               string `xml:"primary_purpose"`                // Treatment, Treatment, Pre...
		Masking                      string `xml:"masking"`                        // Double, Single, None (Ope...
		ObservationalModel           string `xml:"observational_model"`            // Defined Population, Case-...
		TimePerspective              string `xml:"time_perspective"`               // Other, Prospective, Other...
		Allocation                   string `xml:"allocation"`                     // Randomized, Randomized, R...
		MaskingDescription           string `xml:"masking_description"`            // Double blind tablet and p...
		InterventionModelDescription string `xml:"intervention_model_description"` // Naltrexone 50 mg was prov...
	} `xml:"study_design_info"`
	Condition    []string `xml:"condition"` // Congenital Adrenal Hyperp...
	Intervention []struct {
		Text             string   `xml:",chardata"`
		InterventionType string   `xml:"intervention_type"` // Drug, Procedure, Biologic...
		InterventionName string   `xml:"intervention_name"` // Nifedipine, ERP measures ...
		Description      string   `xml:"description"`       // Intracel KLH 1000 mcg (1 ...
		ArmGroupLabel    []string `xml:"arm_group_label"`   // Arm A: Intracel KLH, Arm ...
		OtherName        []string `xml:"other_name"`        // KLH BCI-ImmuneActivator(T...
	} `xml:"intervention"`
	Eligibility struct {
		Text     string `xml:",chardata"`
		Criteria struct {
			Text      string `xml:",chardata"`
			Textblock string `xml:"textblock"` // Inclusion Criteria:    ...
		} `xml:"criteria"`
		Gender            string `xml:"gender"`             // All, Female, All, All, Al...
		MinimumAge        string `xml:"minimum_age"`        // 14 Years, N/A, 18 Years, ...
		MaximumAge        string `xml:"maximum_age"`        // 35 Years, N/A, N/A, 65 Ye...
		HealthyVolunteers string `xml:"healthy_volunteers"` // No, Accepts Healthy Volun...
		StudyPop          struct {
			Text      string `xml:",chardata"`
			Textblock string `xml:"textblock"` // -  Normal volunteers   ...
		} `xml:"study_pop"`
		SamplingMethod    string `xml:"sampling_method"`    // Probability Sample, Non-P...
		GenderBased       string `xml:"gender_based"`       // Yes, Yes, Yes, Yes, Yes, ...
		GenderDescription string `xml:"gender_description"` // males only, relatively he...
	} `xml:"eligibility"`
	Location []struct {
		Text     string `xml:",chardata"`
		Facility struct {
			Text    string `xml:",chardata"`
			Name    string `xml:"name"` // Medical University of Sou...
			Address struct {
				Text    string `xml:",chardata"`
				City    string `xml:"city"`    // Charleston, Minneapolis, ...
				State   string `xml:"state"`   // South Carolina, Minnesota...
				Country string `xml:"country"` // United States, United Sta...
				Zip     string `xml:"zip"`     // 55455, 55455, 53792, 0540...
			} `xml:"address"`
		} `xml:"facility"`
		Status  string `xml:"status"` // Recruiting, Recruiting, R...
		Contact struct {
			Text     string `xml:",chardata"`
			LastName string `xml:"last_name"` // Sandral Hullett, MD, et a...
			Phone    string `xml:"phone"`     // 205-372-3674, 714-992-780...
			Email    string `xml:"email"`     // kleinstein@icare.opt.uab....
			PhoneExt string `xml:"phone_ext"` // TTY8664111010, TTY8664111...
		} `xml:"contact"`
		ContactBackup struct {
			Text     string `xml:",chardata"`
			LastName string `xml:"last_name"` // Caterna Lovaglio, RN/CRA,...
			Phone    string `xml:"phone"`     // 973-754-3778, +416-813-88...
			Email    string `xml:"email"`     // lovaglic@sjhmc.org, phill...
			PhoneExt string `xml:"phone_ext"` // 201594, 5031, 5031, 87522...
		} `xml:"contact_backup"`
		Investigator []struct {
			Text     string `xml:",chardata"`
			LastName string `xml:"last_name"` // Paul Newhouse, M.D., Robe...
			Role     string `xml:"role"`      // Principal Investigator, P...
		} `xml:"investigator"`
	} `xml:"location"`
	LocationCountries struct {
		Text    string   `xml:",chardata"`
		Country []string `xml:"country"` // United States, United Sta...
	} `xml:"location_countries"`
	VerificationDate      string `xml:"verification_date"`        // January 2004, December 20...
	StudyFirstSubmitted   string `xml:"study_first_submitted"`    // November 3, 1999, Novembe...
	StudyFirstSubmittedQc string `xml:"study_first_submitted_qc"` // November 3, 1999, Novembe...
	StudyFirstPosted      struct {
		Text string `xml:",chardata"` // November 4, 1999, Novembe...
		Type string `xml:"type,attr"`
	} `xml:"study_first_posted"`
	LastUpdateSubmitted   string `xml:"last_update_submitted"`    // June 23, 2005, June 23, 2...
	LastUpdateSubmittedQc string `xml:"last_update_submitted_qc"` // June 23, 2005, June 23, 2...
	LastUpdatePosted      struct {
		Text string `xml:",chardata"` // June 24, 2005, June 24, 2...
		Type string `xml:"type,attr"`
	} `xml:"last_update_posted"`
	ConditionBrowse struct {
		Text     string   `xml:",chardata"`
		MeshTerm []string `xml:"mesh_term"` // Adrenal Hyperplasia, Cong...
	} `xml:"condition_browse"`
	InterventionBrowse struct {
		Text     string   `xml:",chardata"`
		MeshTerm []string `xml:"mesh_term"` // Nifedipine, Freund's Adju...
	} `xml:"intervention_browse"`
	Keyword       []string `xml:"keyword"`        // lead overburden, Rheumato...
	OfficialTitle string   `xml:"official_title"` // Vaccination With Tetanus ...
	OversightInfo struct {
		Text                 string `xml:",chardata"`
		HasDmc               string `xml:"has_dmc"`                 // Yes, Yes, Yes, Yes, Yes, ...
		IsFdaRegulatedDrug   string `xml:"is_fda_regulated_drug"`   // No, Yes, Yes, No, No, Yes...
		IsFdaRegulatedDevice string `xml:"is_fda_regulated_device"` // No, No, No, No, No, No, N...
		IsUsExport           string `xml:"is_us_export"`            // No, No, No, No, No, No, N...
		IsUnapprovedDevice   string `xml:"is_unapproved_device"`    // Yes, Yes, Yes, Yes, Yes, ...
		IsPpsd               string `xml:"is_ppsd"`                 // Yes, Yes, Yes, Yes, Yes, ...
	} `xml:"oversight_info"`
	WhyStopped string `xml:"why_stopped"` // Replaced by another study...
	StartDate  struct {
		Text string `xml:",chardata"` // July 2002, September 1997...
		Type string `xml:"type,attr"`
	} `xml:"start_date"`
	CompletionDate struct {
		Text string `xml:",chardata"` // March 2012, September 201...
		Type string `xml:"type,attr"`
	} `xml:"completion_date"`
	PrimaryCompletionDate struct {
		Text string `xml:",chardata"` // March 2012, October 2001,...
		Type string `xml:"type,attr"`
	} `xml:"primary_completion_date"`
	PrimaryOutcome []struct {
		Text        string `xml:",chardata"`
		Measure     string `xml:"measure"`     // To assess whether patient...
		TimeFrame   string `xml:"time_frame"`  // Week 4 post vaccination, ...
		Description string `xml:"description"` // Comparison of the cumulat...
	} `xml:"primary_outcome"`
	SecondaryOutcome []struct {
		Text        string `xml:",chardata"`
		Measure     string `xml:"measure"`     // Tetanus Response, Axial l...
		TimeFrame   string `xml:"time_frame"`  // Throughout study, 5 years...
		Description string `xml:"description"` // Four questionnaires were ...
	} `xml:"secondary_outcome"`
	NumberOfGroups string `xml:"number_of_groups"` // 3, 3, 2, 2, 1, 1, 4, 2, 3...
	Enrollment     struct {
		Text string `xml:",chardata"` // 112, 469, 1636, 279, 209,...
		Type string `xml:"type,attr"`
	} `xml:"enrollment"`
	ArmGroup []struct {
		Text          string `xml:",chardata"`
		ArmGroupLabel string `xml:"arm_group_label"` // Arm A: Intracel KLH, Arm ...
		Description   string `xml:"description"`     // Intracel KLH 1000 mcg (1 ...
		ArmGroupType  string `xml:"arm_group_type"`  // Experimental, Active Comp...
	} `xml:"arm_group"`
	BiospecRetention string `xml:"biospec_retention"` // Samples With DNA, Samples...
	BiospecDescr     struct {
		Text      string `xml:",chardata"`
		Textblock string `xml:"textblock"` // analysis of blood samples...
	} `xml:"biospec_descr"`
	OverallOfficial []struct {
		Text        string `xml:",chardata"`
		LastName    string `xml:"last_name"`   // Jeffrey Miller, MD, Jane ...
		Role        string `xml:"role"`        // Principal Investigator, S...
		Affiliation string `xml:"affiliation"` // Masonic Cancer Center, Un...
	} `xml:"overall_official"`
	ResponsibleParty struct {
		Text                    string `xml:",chardata"`
		ResponsiblePartyType    string `xml:"responsible_party_type"`   // Sponsor, Sponsor, Princip...
		InvestigatorAffiliation string `xml:"investigator_affiliation"` // Johns Hopkins Bloomberg S...
		InvestigatorFullName    string `xml:"investigator_full_name"`   // Curtis Meinert, Curtis Me...
		InvestigatorTitle       string `xml:"investigator_title"`       // Curtis Meinert, PhD, Prof...
		NameTitle               string `xml:"name_title"`               // John Paul SanGiovanni, Sc...
		Organization            string `xml:"organization"`             // National Eye Institute, N...
	} `xml:"responsible_party"`
	LastKnownStatus string `xml:"last_known_status"` // Active, not recruiting, A...
	OverallContact  struct {
		Text     string `xml:",chardata"`
		LastName string `xml:"last_name"` // Sonia Caprio, M.D., Lisa ...
		Phone    string `xml:"phone"`     // 1-203-764-5692, 1-614-292...
		Email    string `xml:"email"`     // sonia.caprio@yale.edu, jo...
		PhoneExt string `xml:"phone_ext"` // 100, 48195, 2042, 7072, 8...
	} `xml:"overall_contact"`
	NumberOfArms string `xml:"number_of_arms"` // 2, 2, 3, 2, 2, 3, 2, 4, 1...
	Link         []struct {
		Text        string `xml:",chardata"`
		URL         string `xml:"url"`         // http://www.nei.nih.gov/he...
		Description string `xml:"description"` // NEI Clinical Studies Data...
	} `xml:"link"`
	ResultsReference []struct {
		Text     string `xml:",chardata"`
		Citation string `xml:"citation"` // Gwiazda J, Hyman L, Husse...
		PMID     string `xml:"PMID"`     // 12657584, 15223788, 16009...
	} `xml:"results_reference"`
	Reference []struct {
		Text     string `xml:",chardata"`
		Citation string `xml:"citation"` // Berson EL, Rosner B, Sand...
		PMID     string `xml:"PMID"`     // 8512476, 8675413, 8684794...
	} `xml:"reference"`
	Acronym                 string `xml:"acronym"`                    // OHTS, CRRT, MACRT, FGCRT,...
	ResultsFirstSubmitted   string `xml:"results_first_submitted"`    // March 6, 2015, June 15, 2...
	ResultsFirstSubmittedQc string `xml:"results_first_submitted_qc"` // March 6, 2015, August 11,...
	ResultsFirstPosted      struct {
		Text string `xml:",chardata"` // March 19, 2015, September...
		Type string `xml:"type,attr"`
	} `xml:"results_first_posted"`
	ProvidedDocumentSection struct {
		Text             string `xml:",chardata"`
		ProvidedDocument []struct {
			Text                string `xml:",chardata"`
			DocumentType        string `xml:"document_type"`         // Informed Consent Form, St...
			DocumentHasProtocol string `xml:"document_has_protocol"` // No, Yes, No, Yes, Yes, Ye...
			DocumentHasIcf      string `xml:"document_has_icf"`      // Yes, No, No, No, No, No, ...
			DocumentHasSap      string `xml:"document_has_sap"`      // No, No, Yes, Yes, Yes, Ye...
			DocumentDate        string `xml:"document_date"`         // February 6, 2019, April 1...
			DocumentURL         string `xml:"document_url"`          // https://ClinicalTrials.go...
		} `xml:"provided_document"`
	} `xml:"provided_document_section"`
	ClinicalResults struct {
		Text            string `xml:",chardata"`
		ParticipantFlow struct {
			Text      string `xml:",chardata"`
			GroupList struct {
				Text  string `xml:",chardata"`
				Group []struct {
					Text        string `xml:",chardata"`
					GroupID     string `xml:"group_id,attr"`
					Title       string `xml:"title"`       // Observation, Treatment, I...
					Description string `xml:"description"` // Close Observation, Topica...
				} `xml:"group"`
			} `xml:"group_list"`
			PeriodList struct {
				Text   string `xml:",chardata"`
				Period []struct {
					Text          string `xml:",chardata"`
					Title         string `xml:"title"` // Overall Study, Overall St...
					MilestoneList struct {
						Text      string `xml:",chardata"`
						Milestone []struct {
							Text             string `xml:",chardata"`
							Title            string `xml:"title"` // STARTED, Completed OHTS P...
							ParticipantsList struct {
								Text         string `xml:",chardata"`
								Participants []struct {
									Text    string `xml:",chardata"` // Completed OHTS Phase 2, t...
									GroupID string `xml:"group_id,attr"`
									Count   string `xml:"count,attr"`
								} `xml:"participants"`
							} `xml:"participants_list"`
						} `xml:"milestone"`
					} `xml:"milestone_list"`
					DropWithdrawReasonList struct {
						Text               string `xml:",chardata"`
						DropWithdrawReason []struct {
							Text             string `xml:",chardata"`
							Title            string `xml:"title"` // Death, Lack of Efficacy, ...
							ParticipantsList struct {
								Text         string `xml:",chardata"`
								Participants []struct {
									Text    string `xml:",chardata"`
									GroupID string `xml:"group_id,attr"`
									Count   string `xml:"count,attr"`
								} `xml:"participants"`
							} `xml:"participants_list"`
						} `xml:"drop_withdraw_reason"`
					} `xml:"drop_withdraw_reason_list"`
				} `xml:"period"`
			} `xml:"period_list"`
			RecruitmentDetails   string `xml:"recruitment_details"`    // December 1992, Randomizat...
			PreAssignmentDetails string `xml:"pre_assignment_details"` // Two hundred and nine pati...
		} `xml:"participant_flow"`
		Baseline struct {
			Text       string `xml:",chardata"`
			Population string `xml:"population"` // 1636 ocular hypertensive ...
			GroupList  struct {
				Text  string `xml:",chardata"`
				Group []struct {
					Text        string `xml:",chardata"`
					GroupID     string `xml:"group_id,attr"`
					Title       string `xml:"title"`       // Observation, Treatment, T...
					Description string `xml:"description"` // Observation only, Topical...
				} `xml:"group"`
			} `xml:"group_list"`
			AnalyzedList struct {
				Text     string `xml:",chardata"`
				Analyzed []struct {
					Text      string `xml:",chardata"`
					Units     string `xml:"units"` // Participants, Participant...
					Scope     string `xml:"scope"` // Overall, Overall, Overall...
					CountList struct {
						Text  string `xml:",chardata"`
						Count []struct {
							Text    string `xml:",chardata"`
							GroupID string `xml:"group_id,attr"`
							Value   string `xml:"value,attr"`
						} `xml:"count"`
					} `xml:"count_list"`
				} `xml:"analyzed"`
			} `xml:"analyzed_list"`
			MeasureList struct {
				Text    string `xml:",chardata"`
				Measure []struct {
					Text       string `xml:",chardata"`
					Title      string `xml:"title"`      // Age, Sex: Female, Male, R...
					Units      string `xml:"units"`      // years, Participants, part...
					Param      string `xml:"param"`      // Mean, Count of Participan...
					Dispersion string `xml:"dispersion"` // Standard Deviation, Stand...
					ClassList  struct {
						Text  string `xml:",chardata"`
						Class []struct {
							Text         string `xml:",chardata"`
							CategoryList struct {
								Text     string `xml:",chardata"`
								Category []struct {
									Text            string `xml:",chardata"`
									MeasurementList struct {
										Text        string `xml:",chardata"`
										Measurement []struct {
											Text       string `xml:",chardata"` // These numbers reflect two...
											GroupID    string `xml:"group_id,attr"`
											Value      string `xml:"value,attr"`
											Spread     string `xml:"spread,attr"`
											LowerLimit string `xml:"lower_limit,attr"`
											UpperLimit string `xml:"upper_limit,attr"`
										} `xml:"measurement"`
									} `xml:"measurement_list"`
									Title string `xml:"title"` // Female, Male, <=18 years,...
								} `xml:"category"`
							} `xml:"category_list"`
							Title        string `xml:"title"` // Native American, Asian, A...
							AnalyzedList struct {
								Text     string `xml:",chardata"`
								Analyzed []struct {
									Text      string `xml:",chardata"`
									Units     string `xml:"units"` // Participants, Participant...
									Scope     string `xml:"scope"` // Class, Class, Class, Clas...
									CountList struct {
										Text  string `xml:",chardata"`
										Count []struct {
											Text    string `xml:",chardata"`
											GroupID string `xml:"group_id,attr"`
											Value   string `xml:"value,attr"`
										} `xml:"count"`
									} `xml:"count_list"`
								} `xml:"analyzed"`
							} `xml:"analyzed_list"`
						} `xml:"class"`
					} `xml:"class_list"`
					Description   string `xml:"description"`    // Information is not availa...
					UnitsAnalyzed string `xml:"units_analyzed"` // Participants, Participant...
					Population    string `xml:"population"`     // Continuous age data were ...
					AnalyzedList  struct {
						Text     string `xml:",chardata"`
						Analyzed []struct {
							Text      string `xml:",chardata"`
							Units     string `xml:"units"` // Participants, community, ...
							Scope     string `xml:"scope"` // Measure, Measure, Measure...
							CountList struct {
								Text  string `xml:",chardata"`
								Count []struct {
									Text    string `xml:",chardata"`
									GroupID string `xml:"group_id,attr"`
									Value   string `xml:"value,attr"`
								} `xml:"count"`
							} `xml:"count_list"`
						} `xml:"analyzed"`
					} `xml:"analyzed_list"`
				} `xml:"measure"`
			} `xml:"measure_list"`
		} `xml:"baseline"`
		OutcomeList struct {
			Text    string `xml:",chardata"`
			Outcome []struct {
				Text        string `xml:",chardata"`
				Type        string `xml:"type"`        // Primary, Primary, Primary...
				Title       string `xml:"title"`       // Incidence of Primary Open...
				Description string `xml:"description"` // Comparison of the cumulat...
				TimeFrame   string `xml:"time_frame"`  // 5 yrs (OHTS I, June 2002)...
				Population  string `xml:"population"`  // 1636 ocular hypertensive ...
				GroupList   struct {
					Text  string `xml:",chardata"`
					Group []struct {
						Text        string `xml:",chardata"`
						GroupID     string `xml:"group_id,attr"`
						Title       string `xml:"title"`       // Observation, Treatment, I...
						Description string `xml:"description"` // Observation only from Feb...
					} `xml:"group"`
				} `xml:"group_list"`
				Measure struct {
					Text         string `xml:",chardata"`
					Title        string `xml:"title"`       // Incidence of Primary Open...
					Description  string `xml:"description"` // Comparison of the cumulat...
					Population   string `xml:"population"`  // 1636 ocular hypertensive ...
					Units        string `xml:"units"`       // percent of participants, ...
					Param        string `xml:"param"`       // Number, Number, Number, N...
					AnalyzedList struct {
						Text     string `xml:",chardata"`
						Analyzed []struct {
							Text      string `xml:",chardata"`
							Units     string `xml:"units"` // Participants, Participant...
							Scope     string `xml:"scope"` // Measure, Measure, Measure...
							CountList struct {
								Text  string `xml:",chardata"`
								Count []struct {
									Text    string `xml:",chardata"`
									GroupID string `xml:"group_id,attr"`
									Value   string `xml:"value,attr"`
								} `xml:"count"`
							} `xml:"count_list"`
						} `xml:"analyzed"`
					} `xml:"analyzed_list"`
					ClassList struct {
						Text  string `xml:",chardata"`
						Class []struct {
							Text         string `xml:",chardata"`
							Title        string `xml:"title"` // Incidence of glaucoma at ...
							CategoryList struct {
								Text     string `xml:",chardata"`
								Category []struct {
									Text            string `xml:",chardata"`
									MeasurementList struct {
										Text        string `xml:",chardata"`
										Measurement []struct {
											Text       string `xml:",chardata"` // The upper end of the conf...
											GroupID    string `xml:"group_id,attr"`
											Value      string `xml:"value,attr"`
											Spread     string `xml:"spread,attr"`
											LowerLimit string `xml:"lower_limit,attr"`
											UpperLimit string `xml:"upper_limit,attr"`
										} `xml:"measurement"`
									} `xml:"measurement_list"`
									Title string `xml:"title"` // CR/CCR, Progressed, Not e...
								} `xml:"category"`
							} `xml:"category_list"`
							AnalyzedList struct {
								Text     string `xml:",chardata"`
								Analyzed []struct {
									Text      string `xml:",chardata"`
									Units     string `xml:"units"` // Participants, Participant...
									Scope     string `xml:"scope"` // Class, Class, Class, Clas...
									CountList struct {
										Text  string `xml:",chardata"`
										Count []struct {
											Text    string `xml:",chardata"`
											GroupID string `xml:"group_id,attr"`
											Value   string `xml:"value,attr"`
										} `xml:"count"`
									} `xml:"count_list"`
								} `xml:"analyzed"`
							} `xml:"analyzed_list"`
						} `xml:"class"`
					} `xml:"class_list"`
					Dispersion    string `xml:"dispersion"`     // Standard Error, Standard ...
					UnitsAnalyzed string `xml:"units_analyzed"` // Participants, lesions on ...
				} `xml:"measure"`
				AnalysisList struct {
					Text     string `xml:",chardata"`
					Analysis []struct {
						Text        string `xml:",chardata"`
						GroupIDList struct {
							Text    string   `xml:",chardata"`
							GroupID []string `xml:"group_id"` // O1, O2, O1, O2, O1, O2, O...
						} `xml:"group_id_list"`
						GroupsDesc            string `xml:"groups_desc"`               // logistic regression and m...
						NonInferiorityType    string `xml:"non_inferiority_type"`      // Superiority or Other, Sup...
						PValue                string `xml:"p_value"`                   // <0.05, 0.18, 0.12, 0.02, ...
						PValueDesc            string `xml:"p_value_desc"`              // actual calculation, P-val...
						Method                string `xml:"method"`                    // Regression, Logistic, ANO...
						ParamType             string `xml:"param_type"`                // Hazard Ratio (HR), Hazard...
						ParamValue            string `xml:"param_value"`               // 0.91, 1.19, 0.88, 0.59, 0...
						CiPercent             string `xml:"ci_percent"`                // 95, 95, 95, 95, 95, 95, 9...
						CiNSides              string `xml:"ci_n_sides"`                // 2-Sided, 2-Sided, 2-Sided...
						CiLowerLimit          string `xml:"ci_lower_limit"`            // 0.81, 1.03, 0.73, 0.39, 0...
						CiUpperLimit          string `xml:"ci_upper_limit"`            // 1.03, 1.38, 1.06, 0.89, 1...
						MethodDesc            string `xml:"method_desc"`               // Adjustment for the seven ...
						EstimateDesc          string `xml:"estimate_desc"`             // Reference level = Hormone...
						NonInferiorityDesc    string `xml:"non_inferiority_desc"`      // The overall type I error ...
						OtherAnalysisDesc     string `xml:"other_analysis_desc"`       // Reference level = placebo...
						DispersionType        string `xml:"dispersion_type"`           // Standard Error of the Mea...
						DispersionValue       string `xml:"dispersion_value"`          // .514, .327, .524, 0.0698,...
						CiUpperLimitNaComment string `xml:"ci_upper_limit_na_comment"` // The upper bound of 95% CI...
					} `xml:"analysis"`
				} `xml:"analysis_list"`
				PostingDate string `xml:"posting_date"` // 01/2021, 06/2022, 06/2022...
			} `xml:"outcome"`
		} `xml:"outcome_list"`
		ReportedEvents struct {
			Text      string `xml:",chardata"`
			TimeFrame string `xml:"time_frame"` // Adverse events collected ...
			Desc      string `xml:"desc"`       // Specific ocular adverse e...
			GroupList struct {
				Text  string `xml:",chardata"`
				Group []struct {
					Text        string `xml:",chardata"`
					GroupID     string `xml:"group_id,attr"`
					Title       string `xml:"title"`       // Observation, Treatment, I...
					Description string `xml:"description"` // Observation only from Feb...
				} `xml:"group"`
			} `xml:"group_list"`
			SeriousEvents struct {
				Text              string `xml:",chardata"`
				DefaultAssessment string `xml:"default_assessment"` // Systematic Assessment, Sy...
				CategoryList      struct {
					Text     string `xml:",chardata"`
					Category []struct {
						Text      string `xml:",chardata"`
						Title     string `xml:"title"` // Total, Eye disorders, Tot...
						EventList struct {
							Text  string `xml:",chardata"`
							Event []struct {
								Text     string `xml:",chardata"`
								SubTitle struct {
									Text  string `xml:",chardata"` // Total, serious adverse ev...
									Vocab string `xml:"vocab,attr"`
								} `xml:"sub_title"`
								Counts []struct {
									Text             string `xml:",chardata"`
									GroupID          string `xml:"group_id,attr"`
									SubjectsAffected string `xml:"subjects_affected,attr"`
									SubjectsAtRisk   string `xml:"subjects_at_risk,attr"`
									Events           string `xml:"events,attr"`
								} `xml:"counts"`
								Description string `xml:"description"` // Specific ocular serious a...
								Assessment  string `xml:"assessment"`  // Systematic Assessment, Sy...
							} `xml:"event"`
						} `xml:"event_list"`
					} `xml:"category"`
				} `xml:"category_list"`
				DefaultVocab string `xml:"default_vocab"` // serious, ICD, MedDRA (9.0...
			} `xml:"serious_events"`
			OtherEvents struct {
				Text               string `xml:",chardata"`
				FrequencyThreshold string `xml:"frequency_threshold"` // 0, 1, 0, 0, 5, 0, 0, 5, 4...
				DefaultAssessment  string `xml:"default_assessment"`  // Systematic Assessment, Sy...
				CategoryList       struct {
					Text     string `xml:",chardata"`
					Category []struct {
						Text      string `xml:",chardata"`
						Title     string `xml:"title"` // Total, Eye disorders, Tot...
						EventList struct {
							Text  string `xml:",chardata"`
							Event []struct {
								Text     string `xml:",chardata"`
								SubTitle struct {
									Text  string `xml:",chardata"` // Total, other adverse even...
									Vocab string `xml:"vocab,attr"`
								} `xml:"sub_title"`
								Counts []struct {
									Text             string `xml:",chardata"`
									GroupID          string `xml:"group_id,attr"`
									SubjectsAffected string `xml:"subjects_affected,attr"`
									SubjectsAtRisk   string `xml:"subjects_at_risk,attr"`
									Events           string `xml:"events,attr"`
								} `xml:"counts"`
								Description string `xml:"description"` // Adverse Events that were ...
								Assessment  string `xml:"assessment"`  // Systematic Assessment, Sy...
							} `xml:"event"`
						} `xml:"event_list"`
					} `xml:"category"`
				} `xml:"category_list"`
				DefaultVocab string `xml:"default_vocab"` // other, ICD, MedDRA (9.0),...
			} `xml:"other_events"`
		} `xml:"reported_events"`
		CertainAgreements struct {
			Text                 string `xml:",chardata"`
			PiEmployee           string `xml:"pi_employee"`           // Principal Investigators a...
			RestrictiveAgreement string `xml:"restrictive_agreement"` // There is NOT an agreement...
		} `xml:"certain_agreements"`
		PointOfContact struct {
			Text         string `xml:",chardata"`
			NameOrTitle  string `xml:"name_or_title"` // Michael Kass MD, Curtis M...
			Organization string `xml:"organization"`  // Washington University Sch...
			Phone        string `xml:"phone"`         // 314-362-5713, 410-955-819...
			Email        string `xml:"email"`         // kass@vision.wustl.edu, cm...
		} `xml:"point_of_contact"`
		LimitationsAndCaveats string `xml:"limitations_and_caveats"` // A biased sample may have ...
	} `xml:"clinical_results"`
	PatientData struct {
		Text              string   `xml:",chardata"`
		SharingIpd        string   `xml:"sharing_ipd"`         // Yes, No, No, No, No, No, ...
		IpdDescription    string   `xml:"ipd_description"`     // Not required when trial w...
		IpdInfoType       []string `xml:"ipd_info_type"`       // Study Protocol, Clinical ...
		IpdTimeFrame      string   `xml:"ipd_time_frame"`      // Available since 2009, Dat...
		IpdURL            string   `xml:"ipd_url"`             // https://www.niddkreposito...
		IpdAccessCriteria string   `xml:"ipd_access_criteria"` // Data can accessed from JH...
	} `xml:"patient_data"`
	RemovedCountries struct {
		Text    string   `xml:",chardata"`
		Country []string `xml:"country"` // United States, Puerto Ric...
	} `xml:"removed_countries"`
	OtherOutcome []struct {
		Text        string `xml:",chardata"`
		Measure     string `xml:"measure"`     // Change in Brief Psychotic...
		TimeFrame   string `xml:"time_frame"`  // Baseline, Week 8, Baselin...
		Description string `xml:"description"` // $US, Bleeding in ECCO2R s...
	} `xml:"other_outcome"`
	PendingResults struct {
		Text               string   `xml:",chardata"`
		Submitted          []string `xml:"submitted"`           // December 22, 2015, Novemb...
		Returned           []string `xml:"returned"`            // February 1, 2016, Decembe...
		SubmissionCanceled []string `xml:"submission_canceled"` // Unknown, August 15, 2018,...
	} `xml:"pending_results"`
	StudyDocs struct {
		Text     string `xml:",chardata"`
		StudyDoc []struct {
			Text       string `xml:",chardata"`
			DocID      string `xml:"doc_id"`      // CABG, PATHS, DIG, ACIP, H...
			DocType    string `xml:"doc_type"`    // Individual Participant Da...
			DocURL     string `xml:"doc_url"`     // http://biolincc.nhlbi.nih...
			DocComment string `xml:"doc_comment"` // NHLBI provides controlled...
		} `xml:"study_doc"`
	} `xml:"study_docs"`
	OverallContactBackup struct {
		Text     string `xml:",chardata"`
		LastName string `xml:"last_name"` // Joanna Klubo-Gwiezdzinska...
		Phone    string `xml:"phone"`     // (301) 496-5052, (301) 496...
		Email    string `xml:"email"`     // joanna.klubo-gwiezdzinska...
		PhoneExt string `xml:"phone_ext"` // 2039, 50 31, 8112, 75228,...
	} `xml:"overall_contact_backup"`
	DispositionFirstSubmitted   string `xml:"disposition_first_submitted"`    // April 13, 2011, April 13,...
	DispositionFirstSubmittedQc string `xml:"disposition_first_submitted_qc"` // April 13, 2011, April 13,...
	DispositionFirstPosted      struct {
		Text string `xml:",chardata"` // April 25, 2011, April 25,...
		Type string `xml:"type,attr"`
	} `xml:"disposition_first_posted"`
	TargetDuration     string `xml:"target_duration"` // 36 Months, 4 Weeks, 12 Mo...
	ExpandedAccessInfo struct {
		Text                           string `xml:",chardata"`
		ExpandedAccessTypeIntermediate string `xml:"expanded_access_type_intermediate"` // Yes, Yes, Yes, Yes, Yes, ...
		ExpandedAccessTypeTreatment    string `xml:"expanded_access_type_treatment"`    // Yes, Yes, Yes, Yes, Yes, ...
		ExpandedAccessTypeIndividual   string `xml:"expanded_access_type_individual"`   // Yes, Yes, Yes, Yes, Yes, ...
	} `xml:"expanded_access_info"`
}

type PubMedArticle struct {
	XMLName        xml.Name `xml:"article"`
	Text           string   `xml:",chardata"`
	Mml            string   `xml:"mml,attr"`
	Xlink          string   `xml:"xlink,attr"`
	Ali            string   `xml:"ali,attr"`
	ArticleType    string   `xml:"article-type,attr"`
	DtdVersion     string   `xml:"dtd-version,attr"`
	ProcessingMeta struct {
		Text          string `xml:",chardata"`
		BaseTagset    string `xml:"base-tagset,attr"`
		MathmlVersion string `xml:"mathml-version,attr"`
		TableModel    string `xml:"table-model,attr"`
		TagsetFamily  string `xml:"tagset-family,attr"`
		RestrictedBy  string `xml:"restricted-by"` // pmc
	} `xml:"processing-meta"`
	Front struct {
		Text        string `xml:",chardata"`
		JournalMeta struct {
			Text      string `xml:",chardata"`
			JournalID []struct {
				Text          string `xml:",chardata"` // Trials, Trials
				JournalIDType string `xml:"journal-id-type,attr"`
			} `xml:"journal-id"`
			JournalTitleGroup struct {
				Text         string `xml:",chardata"`
				JournalTitle string `xml:"journal-title"` // Trials
			} `xml:"journal-title-group"`
			ISSN struct {
				Text    string `xml:",chardata"` // 1745-6215
				PubType string `xml:"pub-type,attr"`
			} `xml:"issn"`
			Publisher struct {
				Text          string `xml:",chardata"`
				PublisherName string `xml:"publisher-name"` // BioMed Central
				PublisherLoc  string `xml:"publisher-loc"`  // London
			} `xml:"publisher"`
		} `xml:"journal-meta"`
		ArticleMeta struct {
			Text      string `xml:",chardata"`
			ArticleID []struct {
				Text      string `xml:",chardata"` // 35078536, 8790842, 5798, ...
				PubIDType string `xml:"pub-id-type,attr"`
			} `xml:"article-id"`
			ArticleCategories struct {
				Text      string `xml:",chardata"`
				SubjGroup struct {
					Text          string `xml:",chardata"`
					SubjGroupType string `xml:"subj-group-type,attr"`
					Subject       string `xml:"subject"` // Study Protocol
				} `xml:"subj-group"`
			} `xml:"article-categories"`
			TitleGroup struct {
				Text         string `xml:",chardata"`
				ArticleTitle string `xml:"article-title"` // Understanding and restori...
			} `xml:"title-group"`
			ContribGroup struct {
				Text    string `xml:",chardata"`
				Contrib []struct {
					Text        string `xml:",chardata"`
					ContribType string `xml:"contrib-type,attr"`
					Corresp     string `xml:"corresp,attr"`
					ContribID   struct {
						Text          string `xml:",chardata"` // http://orcid.org/0000-000...
						ContribIDType string `xml:"contrib-id-type,attr"`
					} `xml:"contrib-id"`
					Name struct {
						Text       string `xml:",chardata"`
						Surname    string `xml:"surname"`     // Ledermann, von Känel, Be...
						GivenNames string `xml:"given-names"` // K., R., C., H., M., J., E...
					} `xml:"name"`
					Address struct {
						Text  string `xml:",chardata"`
						Email string `xml:"email"` // katharina.ledermann@unifr...
					} `xml:"address"`
					Xref []struct {
						Text    string `xml:",chardata"` // 1, 2, 1, 3, 4, 2, 5, 6, 2...
						RefType string `xml:"ref-type,attr"`
						Rid     string `xml:"rid,attr"`
					} `xml:"xref"`
				} `xml:"contrib"`
				Aff []struct {
					Text            string `xml:",chardata"` // Zurich, Switzerland, Rue ...
					ID              string `xml:"id,attr"`
					Label           string `xml:"label"` // 1, 2, 3, 4, 5, 6
					InstitutionWrap struct {
						Text          string `xml:",chardata"`
						InstitutionID []struct {
							Text              string `xml:",chardata"` // grid.7400.3, 0000 0004 19...
							InstitutionIDType string `xml:"institution-id-type,attr"`
						} `xml:"institution-id"`
						Institution []string `xml:"institution"` // Department for Consultati...
					} `xml:"institution-wrap"`
				} `xml:"aff"`
			} `xml:"contrib-group"`
			PubDate []struct {
				Text    string `xml:",chardata"`
				PubType string `xml:"pub-type,attr"`
				Day     string `xml:"day"`   // 1, 1
				Month   string `xml:"month"` // 12, 12
				Year    string `xml:"year"`  // 2021, 2021, 2021
			} `xml:"pub-date"`
			Volume      string `xml:"volume"`       // 22
			ElocationID string `xml:"elocation-id"` // 864
			History     struct {
				Text string `xml:",chardata"`
				Date []struct {
					Text     string `xml:",chardata"`
					DateType string `xml:"date-type,attr"`
					Day      string `xml:"day"`   // 23, 4
					Month    string `xml:"month"` // 6, 11
					Year     string `xml:"year"`  // 2021, 2021
				} `xml:"date"`
			} `xml:"history"`
			Permissions struct {
				Text               string `xml:",chardata"`
				CopyrightStatement string `xml:"copyright-statement"` // © The Author(s). 2021
				License            struct {
					Text       string `xml:",chardata"`
					LicenseRef struct {
						Text        string `xml:",chardata"` // https://creativecommons.o...
						SpecificUse string `xml:"specific-use,attr"`
						ContentType string `xml:"content-type,attr"`
					} `xml:"license_ref"`
					LicenseP struct {
						Text    string `xml:",chardata"` // This article is licensed ...
						Bold    string `xml:"bold"`      // Open Access
						ExtLink []struct {
							Text        string `xml:",chardata"` // http://creativecommons.or...
							ExtLinkType string `xml:"ext-link-type,attr"`
							Href        string `xml:"href,attr"`
						} `xml:"ext-link"`
					} `xml:"license-p"`
				} `xml:"license"`
			} `xml:"permissions"`
			Abstract struct {
				Text string `xml:",chardata"`
				ID   string `xml:"id,attr"`
				Sec  []struct {
					Text  string `xml:",chardata"`
					Title string `xml:"title"` // Background, Methods, Disc...
					P     struct {
						Text    string   `xml:",chardata"` // Fibromyalgia (FM) is a ve...
						ID      string   `xml:"id,attr"`
						Italic  []string `xml:"italic"` // N, N, N, N
						ExtLink []struct {
							Text        string `xml:",chardata"` // ClinicalTrials.gov, NCT 0...
							ExtLinkType string `xml:"ext-link-type,attr"`
							Href        string `xml:"href,attr"`
						} `xml:"ext-link"`
					} `xml:"p"`
				} `xml:"sec"`
			} `xml:"abstract"`
			KwdGroup struct {
				Text  string   `xml:",chardata"`
				Lang  string   `xml:"lang,attr"`
				Title string   `xml:"title"` // Keywords
				Kwd   []string `xml:"kwd"`   // Fibromyalgia, Mindfulness...
			} `xml:"kwd-group"`
			FundingGroup struct {
				Text       string `xml:",chardata"`
				AwardGroup struct {
					Text          string `xml:",chardata"`
					FundingSource struct {
						Text            string `xml:",chardata"`
						InstitutionWrap struct {
							Text          string `xml:",chardata"`
							InstitutionID struct {
								Text              string `xml:",chardata"` // http://dx.doi.org/10.1303...
								InstitutionIDType string `xml:"institution-id-type,attr"`
							} `xml:"institution-id"`
							Institution string `xml:"institution"` // Schweizerischer Nationalf...
						} `xml:"institution-wrap"`
					} `xml:"funding-source"`
					AwardID string `xml:"award-id"` // 325130-182766/1
				} `xml:"award-group"`
			} `xml:"funding-group"`
			CustomMetaGroup struct {
				Text       string `xml:",chardata"`
				CustomMeta struct {
					Text      string `xml:",chardata"`
					MetaName  string `xml:"meta-name"`  // issue-copyright-statement...
					MetaValue string `xml:"meta-value"` // © The Author(s) 2021
				} `xml:"custom-meta"`
			} `xml:"custom-meta-group"`
		} `xml:"article-meta"`
	} `xml:"front"`
	Body struct {
		Text string `xml:",chardata"`
		Sec  []struct {
			Text  string `xml:",chardata"`
			ID    string `xml:"id,attr"`
			Title string `xml:"title"` // Administrative informatio...
			P     []struct {
				Text      string `xml:",chardata"` // Note: the numbers in curl...
				ID        string `xml:"id,attr"`
				TableWrap struct {
					Text  string `xml:",chardata"`
					ID    string `xml:"id,attr"`
					Table struct {
						Text  string `xml:",chardata"`
						Frame string `xml:"frame,attr"`
						Rules string `xml:"rules,attr"`
						Tbody struct {
							Text string `xml:",chardata"`
							Tr   []struct {
								Text string `xml:",chardata"`
								Td   []struct {
									Text string `xml:",chardata"` // Title {1}, Trial registra...
									P    []struct {
										Text    string `xml:",chardata"` // Understanding and restori...
										ExtLink []struct {
											Text        string `xml:",chardata"` // ClinicalTrials.gov, https...
											ExtLinkType string `xml:"ext-link-type,attr"`
											Href        string `xml:"href,attr"`
										} `xml:"ext-link"`
										Sup    []string `xml:"sup"`    // 1,2, 1, 3, 4, 2, 5, 6, 2,...
										Italic string   `xml:"italic"` // .
									} `xml:"p"`
								} `xml:"td"`
							} `xml:"tr"`
						} `xml:"tbody"`
					} `xml:"table"`
				} `xml:"table-wrap"`
				Xref []struct {
					Text    string `xml:",chardata"` // 1, 1, 49, 26, 31, 61, 26,...
					Rid     string `xml:"rid,attr"`
					RefType string `xml:"ref-type,attr"`
				} `xml:"xref"`
				Fig struct {
					Text    string `xml:",chardata"`
					ID      string `xml:"id,attr"`
					Label   string `xml:"label"` // Fig. 1
					Caption struct {
						Text string `xml:",chardata"`
						P    string `xml:"p"` // Flowchart of the interven...
					} `xml:"caption"`
					Graphic struct {
						Text string `xml:",chardata"`
						Href string `xml:"href,attr"`
						ID   string `xml:"id,attr"`
					} `xml:"graphic"`
				} `xml:"fig"`
				ExtLink struct {
					Text        string `xml:",chardata"` // ClinicalTrials.gov
					ExtLinkType string `xml:"ext-link-type,attr"`
					Href        string `xml:"href,attr"`
				} `xml:"ext-link"`
			} `xml:"p"`
			Sec []struct {
				Text  string `xml:",chardata"`
				ID    string `xml:"id,attr"`
				Title string `xml:"title"` // Background and rationale ...
				P     []struct {
					Text string `xml:",chardata"` // Fibromyalgia (FM) is a ch...
					ID   string `xml:"id,attr"`
					Xref []struct {
						Text    string `xml:",chardata"` // 72, 67, 47, 58, 6, 13, 17...
						RefType string `xml:"ref-type,attr"`
						Rid     string `xml:"rid,attr"`
					} `xml:"xref"`
					Italic []string `xml:"italic"` // N, N, ., N, N, T, N, N, d...
					List   struct {
						Text     string `xml:",chardata"`
						ListType string `xml:"list-type,attr"`
						ListItem []struct {
							Text string `xml:",chardata"`
							P    struct {
								Text string `xml:",chardata"` // To compare the 18F-DOPA i...
								ID   string `xml:"id,attr"`
							} `xml:"p"`
						} `xml:"list-item"`
					} `xml:"list"`
					Sup     string `xml:"sup"` // 2
					ExtLink struct {
						Text        string `xml:",chardata"` // https://www.sealedenvelop...
						ExtLinkType string `xml:"ext-link-type,attr"`
						Href        string `xml:"href,attr"`
					} `xml:"ext-link"`
					Bold      string `xml:"bold"` // (
					TableWrap struct {
						Text    string `xml:",chardata"`
						ID      string `xml:"id,attr"`
						Label   string `xml:"label"` // Table 2
						Caption struct {
							Text string `xml:",chardata"`
							P    string `xml:"p"` // Schedule of enrollment, i...
						} `xml:"caption"`
						Table struct {
							Text  string `xml:",chardata"`
							Frame string `xml:"frame,attr"`
							Rules string `xml:"rules,attr"`
							Thead struct {
								Text string `xml:",chardata"`
								Tr   []struct {
									Text string `xml:",chardata"`
									Th   []struct {
										Text string `xml:",chardata"` // From June 2021, > 1 d...
										Bold struct {
											Text   string `xml:",chardata"`
											Italic string `xml:"italic"` // -t, t, t, T, T
										} `xml:"bold"`
										Sub struct {
											Text string `xml:",chardata"`
											Bold struct {
												Text   string `xml:",chardata"`
												Italic string `xml:"italic"` // 1, 1, 2, 3
											} `xml:"bold"`
										} `xml:"sub"`
										Sup struct {
											Text string `xml:",chardata"`
											Bold string `xml:"bold"` // 0
										} `xml:"sup"`
									} `xml:"th"`
								} `xml:"tr"`
							} `xml:"thead"`
							Tbody struct {
								Text string `xml:",chardata"`
								Tr   []struct {
									Text string `xml:",chardata"`
									Td   []struct {
										Text string `xml:",chardata"`
										Bold struct {
											Text   string `xml:",chardata"` // Enrolment, Information sc...
											Italic string `xml:"italic"`    // F-DOPA PET scan, MR scan,...
										} `xml:"bold"`
										P []struct {
											Text string `xml:",chardata"`
											Bold struct {
												Text   string `xml:",chardata"`
												Italic string `xml:"italic"` // Medical history, Clinical...
											} `xml:"bold"`
										} `xml:"p"`
									} `xml:"td"`
								} `xml:"tr"`
							} `xml:"tbody"`
						} `xml:"table"`
					} `xml:"table-wrap"`
				} `xml:"p"`
				Sec []struct {
					Text  string `xml:",chardata"`
					ID    string `xml:"id,attr"`
					Title struct {
						Text string `xml:",chardata"` // Main primary outcome, Mai...
						Xref struct {
							Text    string `xml:",chardata"` // 5
							RefType string `xml:"ref-type,attr"`
							Rid     string `xml:"rid,attr"`
						} `xml:"xref"`
					} `xml:"title"`
					P []struct {
						Text string `xml:",chardata"` // 1) A.18F-DOPA influx: the...
						ID   string `xml:"id,attr"`
						Xref []struct {
							Text    string `xml:",chardata"` // 70, 15, 15, 70, 70, 18, 4...
							RefType string `xml:"ref-type,attr"`
							Rid     string `xml:"rid,attr"`
						} `xml:"xref"`
						List struct {
							Text     string `xml:",chardata"`
							ListType string `xml:"list-type,attr"`
							ListItem []struct {
								Text  string `xml:",chardata"`
								Label string `xml:"label"` // 2), 3), 4), 5)
								P     []struct {
									Text string `xml:",chardata"` // The percent BOLD signal c...
									ID   string `xml:"id,attr"`
									Xref []struct {
										Text    string `xml:",chardata"` // 62, 48, 43, 7, 14, 51
										RefType string `xml:"ref-type,attr"`
										Rid     string `xml:"rid,attr"`
									} `xml:"xref"`
								} `xml:"p"`
							} `xml:"list-item"`
						} `xml:"list"`
						Italic  string `xml:"italic"` // Pain severity and functio...
						ExtLink struct {
							Text        string `xml:",chardata"` // https://www.ncbi.nlm.nih....
							ExtLinkType string `xml:"ext-link-type,attr"`
							Href        string `xml:"href,attr"`
						} `xml:"ext-link"`
						Fig struct {
							Text    string `xml:",chardata"`
							ID      string `xml:"id,attr"`
							Label   string `xml:"label"` // Fig. 2
							Caption struct {
								Text string `xml:",chardata"`
								P    string `xml:"p"` // The reward task wheel of ...
							} `xml:"caption"`
							Graphic struct {
								Text string `xml:",chardata"`
								Href string `xml:"href,attr"`
								ID   string `xml:"id,attr"`
							} `xml:"graphic"`
						} `xml:"fig"`
					} `xml:"p"`
					Sec []struct {
						Text  string `xml:",chardata"`
						ID    string `xml:"id,attr"`
						Title string `xml:"title"` // Main outcome 18F-DOPA, Ma...
						P     struct {
							Text string `xml:",chardata"` // State-of-the-art image pr...
							ID   string `xml:"id,attr"`
							Xref []struct {
								Text    string `xml:",chardata"` // 8, 9, 55
								RefType string `xml:"ref-type,attr"`
								Rid     string `xml:"rid,attr"`
							} `xml:"xref"`
							Italic  []string `xml:"italic"` // T, T, f, r, z, z, Z, T-
							ExtLink []struct {
								Text        string `xml:",chardata"` // http://surfer.nmr.mgh.har...
								ExtLinkType string `xml:"ext-link-type,attr"`
								Href        string `xml:"href,attr"`
							} `xml:"ext-link"`
							Sup string `xml:"sup"` // 3
						} `xml:"p"`
					} `xml:"sec"`
				} `xml:"sec"`
			} `xml:"sec"`
			TableWrap struct {
				Text    string `xml:",chardata"`
				ID      string `xml:"id,attr"`
				Label   string `xml:"label"` // Table 1
				Caption struct {
					Text string `xml:",chardata"`
					P    string `xml:"p"` // Questionnaires at assessm...
				} `xml:"caption"`
				Table struct {
					Text  string `xml:",chardata"`
					Frame string `xml:"frame,attr"`
					Rules string `xml:"rules,attr"`
					Thead struct {
						Text string `xml:",chardata"`
						Tr   struct {
							Text string   `xml:",chardata"`
							Th   []string `xml:"th"` // Variables, T0, T1, T2, T3...
						} `xml:"tr"`
					} `xml:"thead"`
					Tbody struct {
						Text string `xml:",chardata"`
						Tr   []struct {
							Text string `xml:",chardata"`
							Td   []struct {
								Text    string `xml:",chardata"` // Demographics: for example...
								Colspan string `xml:"colspan,attr"`
								Bold    string `xml:"bold"` // Sociodemographic and medi...
								Xref    struct {
									Text    string `xml:",chardata"` // 6, 59, 62, 9, 3, 12, 41, ...
									RefType string `xml:"ref-type,attr"`
									Rid     string `xml:"rid,attr"`
								} `xml:"xref"`
							} `xml:"td"`
						} `xml:"tr"`
					} `xml:"tbody"`
				} `xml:"table"`
			} `xml:"table-wrap"`
		} `xml:"sec"`
	} `xml:"body"`
	Back struct {
		Text     string `xml:",chardata"`
		Glossary struct {
			Text    string `xml:",chardata"`
			Title   string `xml:"title"` // Abbreviations
			DefList struct {
				Text    string `xml:",chardata"`
				DefItem []struct {
					Text string `xml:",chardata"`
					Term string `xml:"term"` // AA, AE, BDI, BPI, CAR, CB...
					Def  struct {
						Text string `xml:",chardata"`
						P    struct {
							Text string `xml:",chardata"` // Ambulatory assessment, Ad...
							ID   string `xml:"id,attr"`
						} `xml:"p"`
					} `xml:"def"`
				} `xml:"def-item"`
			} `xml:"def-list"`
		} `xml:"glossary"`
		FnGroup struct {
			Text string `xml:",chardata"`
			Fn   struct {
				Text string `xml:",chardata"`
				P    []struct {
					Text string `xml:",chardata"` // Springer Nature remains n...
					Bold string `xml:"bold"`      // Publisher’s Note
				} `xml:"p"`
			} `xml:"fn"`
		} `xml:"fn-group"`
		Ack struct {
			Text  string `xml:",chardata"`
			Title string `xml:"title"` // Acknowledgements
			P     string `xml:"p"`     // None.
			Sec   []struct {
				Text  string `xml:",chardata"`
				ID    string `xml:"id,attr"`
				Title string `xml:"title"` // Authors’ contributions ...
				P     struct {
					Text string `xml:",chardata"` // The trial was designed an...
					ID   string `xml:"id,attr"`
				} `xml:"p"`
			} `xml:"sec"`
		} `xml:"ack"`
		Notes struct {
			Text  string `xml:",chardata"`
			Title string `xml:"title"` // Declarations
			Notes []struct {
				Text      string `xml:",chardata"`
				ID        string `xml:"id,attr"`
				NotesType string `xml:"notes-type,attr"`
				Title     string `xml:"title"` // Ethics approval and conse...
				P         struct {
					Text string `xml:",chardata"` // Ethics approval was taken...
					ID   string `xml:"id,attr"`
				} `xml:"p"`
			} `xml:"notes"`
		} `xml:"notes"`
		RefList struct {
			Text  string `xml:",chardata"`
			ID    string `xml:"id,attr"`
			Title string `xml:"title"` // References
			Ref   []struct {
				Text            string `xml:",chardata"`
				ID              string `xml:"id,attr"`
				Label           string `xml:"label"` // 1., 2., 3., 4., 5., 6., 7...
				ElementCitation struct {
					Text            string `xml:",chardata"`
					PublicationType string `xml:"publication-type,attr"`
					PersonGroup     []struct {
						Text            string `xml:",chardata"`
						PersonGroupType string `xml:"person-group-type,attr"`
						Name            []struct {
							Text       string `xml:",chardata"`
							Surname    string `xml:"surname"`     // Aman, Jason, Kaye, Urman,...
							GivenNames string `xml:"given-names"` // M, Y, A, R, RA, GT, J, J,...
							Suffix     string `xml:"suffix"`      // Jr, Jr, Jr, 2nd
						} `xml:"name"`
						Etal   string `xml:"etal"`
						Collab string `xml:"collab"` // Group, W
					} `xml:"person-group"`
					ArticleTitle string `xml:"article-title"` // Evidence-based non-pharma...
					Source       string `xml:"source"`        // Curr Pain Headache Rep, A...
					Year         string `xml:"year"`          // 2018, 2006, 2010, 1961, 2...
					Volume       string `xml:"volume"`        // 22, 13, 66, 4, 38, 2012, ...
					Issue        string `xml:"issue"`         // 5, 1, 1, 6, 4, 7, 1, 2, 7...
					Fpage        string `xml:"fpage"`         // 33, 27, 149, 561, 3080, 4...
					PubID        []struct {
						Text      string `xml:",chardata"` // 10.1007/s11916-018-0688-2...
						PubIDType string `xml:"pub-id-type,attr"`
					} `xml:"pub-id"`
					Lpage         string `xml:"lpage"`          // 45, 160, 571, 3088, 42611...
					PublisherLoc  string `xml:"publisher-loc"`  // New York, Durham (NC), Be...
					PublisherName string `xml:"publisher-name"` // Guilford Press, Duke Univ...
				} `xml:"element-citation"`
				MixedCitation struct {
					Text            string `xml:",chardata"` // Berding G, Burchert W, va...
					PublicationType string `xml:"publication-type,attr"`
				} `xml:"mixed-citation"`
			} `xml:"ref"`
		} `xml:"ref-list"`
	} `xml:"back"`
}
